[package]
name = "stemgen"
version = "0.5.0"
edition = "2024"

[workspace]
members = ["cli"]

[lib]
name = "stemgen"
path = "src/lib.rs"

[dependencies]
taglib = { git = "https://github.com/acolombier/taglib-rust.git", tag = "v2.2.0", features = ["use-pkgconfig", "static", "ni-stem"] }
itertools = "0.13.0"
ndarray = { version = "0.17.2"}
ort = { version = "=2.0.0-rc.12", default-features = false, features = ["std","ndarray","download-binaries","tls-rustls"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.143"
sha2 = "0.11.0"
ureq = "3.3.0"

[dependencies.ffmpeg-next]
version = "7.1.0"
default-features = false
features = ["codec","format", "software-resampling", "build"]

[dependencies.chrono]
version = "0.4.41"
optional = true

[features]
default = []
cuda = ["ort/cuda","ort/copy-dylibs" ]
